In [1]:
import pandas as pd

In [2]:
pd.read_json('data/archive/train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

SQL files as dataframe

In [3]:
import mysql.connector

In [5]:
conn = mysql.connector.connect(host='localhost', user='root', password='', database='world')

pd.read_sql_query('SELECT * FROM city', conn)

In [11]:
import requests

In [ ]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=41323766946298f99de097ac9c91de73')

In [ ]:

pd.DataFrame(response.json()['results'])[['id', 'original_title', 'overview', 'vote_average', 'adult']]

(20, 5)

In [29]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [32]:
for i in range(1, 20):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=41323766946298f99de097ac9c91de73&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id', 'original_title', 'overview', 'vote_average', 'adult']]
    df = df.append(temp_df, ignore_index=True)

ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))